receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
        cors:
          allowed_origins: "http://localhost:8082"
          allowed_headers: "*"
  fluentforward:
    endpoint: 0.0.0.0:24224
  prometheus:
    config:
      scrape_configs:
      - job_name: opentelemetry-collector
        scrape_interval: 10s
        static_configs:
        - targets:
          - 0.0.0.0:8888
exporters:
  debug:
  elasticsearch:
    endpoint: http://elasticsearch:9200
    tls:
      insecure: true
    logs_index: ""
    logs_dynamic_index:
        enabled: true
    logstash_format:
        enabled: true
        date_format: "%Y-%m-%d"
  otlp/jaeger:
    endpoint: jaeger-collector:4317
    tls:
      insecure: true
  otlp/tempo:
    endpoint: tempo:4317
    tls:
      insecure: true
  otlphttp/seq:
    endpoint: http://seq:5341/ingest/otlp/
    tls:
      insecure: true
  otlphttp/loki:
    endpoint: http://loki:3100/otlp/
    tls:
      insecure: true
  otlphttp/fluentd:
    endpoint: http://fluentbit:4318
    timeout: 10s
extensions:
  health_check:
    endpoint: 0.0.0.0:13133
  pprof:
    endpoint: 0.0.0.0:1777
  zpages:
    endpoint: 0.0.0.0:55679
processors:
  batch:
    timeout: 10s
    send_batch_size: 10000
    send_batch_max_size: 11000
  memory_limiter:
    check_interval: 5s
    limit_percentage: 80
    spike_limit_percentage: 25
  resource:
    attributes:
      - action: upsert
        key: "elasticsearch.index.prefix"
        from_attribute: "service.name"
service:
  telemetry:
    metrics:
      readers:
      - pull:
          exporter:
            prometheus:
              host: 0.0.0.0
              port: 8888
  extensions:
  - health_check
  - pprof
  - zpages
  pipelines:
    logs:
      receivers:
      - otlp
      - fluentforward
      processors:
      - memory_limiter
      - resource
      - batch
      exporters:
      - otlphttp/seq
      - otlphttp/loki
      - otlphttp/fluentd
      - elasticsearch
    metrics:
      receivers:
      - otlp
      processors:
      - memory_limiter
      - batch
      exporters:
      - debug
    traces:
      receivers:
      - otlp
      processors:
      - memory_limiter
      - batch
      exporters:
      - otlp/jaeger
      - otlp/tempo
