receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317

exporters:
  prometheus:
    endpoint: "0.0.0.0:9090"
    const_labels:
      label1: value1
  otlp:
    endpoint: jaeger-collector:4317
    tls:
      insecure: true
  otlphttp:
    endpoint: "http://seq:5341/ingest/otlp/"
    headers:
      api-key: "X-Seq-ApiKey: p6FrUTYwLz6qakVqRctT"
    tls:
      insecure: true

processors:
  batch:

extensions:
  health_check:
  pprof:
    endpoint: :1888

service:
  extensions: [pprof,  health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp,otlphttp]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [ prometheus]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp]